# test config file
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/metskem/{application}-config.git  # this does not work on cf, it tries but fails ssh because of com.jcraft.jsch.JSchException: UnknownHostKey
          searchPaths: '{profile}'  # make sure you set your profile on the cmdline (not in application.properties), with "--spring.profiles.active=testprofile"
server:
  tomcat:
    basedir: /tmp/tomcat
    accesslog:
      directory: /tmp/accesslog
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

logging:
  level:
    org.springframework.cloud: 'INFO'